/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package platna.lista;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author PC
 */
public class login extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        Toolkit toolkit=getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2-getHeight()/2);
        
        conn = db.java_db();
        danasnjiDan();
    }
    
    public void danasnjiDan(){
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        jMenu2.setText((month +1)+"/"+day+"/"+year);
        
        int second = cal.get(Calendar.SECOND);
        int minut = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        
        jMenu3.setText(hour+":"+(minut)+":"+second);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_korisnik = new javax.swing.JTextField();
        txt_combo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_sifra = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        txt_korisnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_korisnikActionPerformed(evt);
            }
        });
        jPanel1.add(txt_korisnik);
        txt_korisnik.setBounds(300, 310, 120, 30);

        txt_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin" }));
        jPanel1.add(txt_combo);
        txt_combo.setBounds(300, 390, 120, 30);

        jButton1.setText("Prijava");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 430, 65, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Pozicija");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 400, 80, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Sifra:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 360, 29, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Korisnik:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 320, 60, 14);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Unesite Vase korisnicko ime i sifru");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 290, 200, 14);

        txt_sifra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sifraActionPerformed(evt);
            }
        });
        jPanel1.add(txt_sifra);
        txt_sifra.setBounds(300, 350, 120, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/platna/lista/slike/images.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 70, 280, 180);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("OBRAČUN PLATA");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(280, 260, 140, 17);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Time");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_sifraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sifraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sifraActionPerformed

    private void txt_korisnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_korisnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_korisnikActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql ="select korisnik, sifra, pozicija from Korisnici where(korisnik = ? and sifra = ? and pozicija=?)";

        try{
            int count =0;
            pst = conn.prepareStatement(sql);

            pst.setString(1, txt_korisnik.getText());
            pst.setString(2, txt_sifra.getText());
            pst.setString(3, txt_combo.getSelectedItem().toString());

            rs=pst.executeQuery();
            while(rs.next()){

                int id =rs.getInt(1);
                Rdk.rdkId = id;
                count = count+1;
            }

            String ulaz =(txt_combo.getSelectedItem().toString());

            if (ulaz=="Admin"){
                if (count==1){
                    JOptionPane.showMessageDialog(null, "Uspjesno ste se prijavili.");
                    GlavniMeni m =new GlavniMeni();
                    m.setVisible(true);
                    this.dispose();

                }else{
                    JOptionPane.showMessageDialog(null, "Korisnicko ime ili sifra su pogresni");
                }
            }

        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{

            try{
                rs.close();
                pst.close();

            }catch (Exception e){

            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox txt_combo;
    private javax.swing.JTextField txt_korisnik;
    private javax.swing.JPasswordField txt_sifra;
    // End of variables declaration//GEN-END:variables
}
